config/routes.rb
Rails.application.routes.draw do
  resources :genres, only: [:show]
  resources :users
  resources :movies do
    resources :reviews
  end

  resources :movies do
    resources :ratings, only: [:create, :update]
  end

  resource :session, only: [:new, :create, :destroy]

  get "signup" => "users#new"
  get 'search_movies', to: 'movies#search'

  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/characterization.rb
class Characterization < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :characterizations
  has_many :genres, through: :characterizations
  has_many :ratings

  has_many :reviews

  has_many :reviews, dependent: :destroy

  validates :title, :text, presence: true
  validates :text, length: { minimum: 10 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user


  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :ratings

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
            format: { with: /\S+@\S+/ },
            uniqueness: { case_sensitive: false }
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_sign_in, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
    @genres = @movie.genres.order(:name)

  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def search
    if params[:genre_id].present?
      @movies = Movie.joins(:genres).where(genres: { id: params[:genre_id] })
    else
      redirect_to movies_path
    end
  end



  def create
    @movie = Movie.new(movie_params)
    @movie.rating = 0 # инициализация оценки

    if @movie.save
      flash[:notice] = "Movie successfully created!"
      redirect_to @movie
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      flash[:notice] = "Movie successfully updated!"
      redirect_to @movie
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, status: :see_other,
                alert: "Movie successfully deleted!"
  end


  private


  def movie_params
    params.require(:movie).
      permit(:title, :description, :rating, :released_on, :total_gross,
             :director, :duration, :image_file_name, genre_ids: [])
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :require_sign_in

  def create
    @movie = Movie.find(params[:movie_id])
    @rating = @movie.ratings.find_or_initialize_by(user: current_user)
    @rating.update(rating_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @movie }
    end
  end

  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_back(fallback_location: root_path) }
      end
    else
      render :edit
    end
  end


  private

  def rating_params
    params.require(:rating).permit(:stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_sign_in
  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to movie_reviews_path(@movie),
                  notice: "Thanks for your review!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email_or_username]) || User.find_by(name: params[:email_or_username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user),
                  notice: "Welcome back, #{user.name}!"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other,
                notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other,
                alert: "Account successfully deleted!"
  end


  private

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end
  def require_correct_user
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, status: :see_other unless current_user?(@user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def average_stars(movie)
    if movie.ratings.count > 0
      average = movie.ratings.average(:stars)
      "Average rating: #{'%.1f' % average} / 10"
    else
      "No ratings yet"
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="header">
    <ul class="left">
      <li>
        <%= link_to "All Movies", movies_path, class: "button" %>
      </li>

      <li class="search-container">
        <%= form_with url: search_movies_path, method: :get, local: true do |form| %>
          <%= form.label :genre_id, 'Search by genre:' %>
          <%= form.select :genre_id, Genre.all.collect { |g| [g.name, g.id] }, include_blank: 'All genres' %>
          <%= form.submit 'Search', class: 'button' %>
        <% end %>
      </li>

    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path,
                      data: { turbo_method: :delete },
                      class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_session_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/header" %>
  <head>

    <title>Imdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>
  </head>

  <body>
  <div class="content">
    <%= render "layouts/flash" %>

    <%= yield %>
  </div>
  </body>

  <%= render "layouts/footer" %>

</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>